app/models/Migration.php
<?php

namespace app\models;

use core\base\Model;

/**
 *
 */
class Migration extends Model
{
    /**
     * @return void
     */
    public function createUserTable()
    {
        $db = static::getDB();

        $sql = 'CREATE TABLE IF NOT EXISTS user(
            id INT NOT NULL AUTO_INCREMENT,
            PRIMARY KEY(id),
            username VARCHAR(255) NOT NULL,
            password VARCHAR(255) NOT NULL,
            balance DOUBLE NOT NULL
        )';

        $db->prepare($sql)->execute();

        $sql = 'CREATE INDEX `idx-user-username`
            ON user(username)';

        $db->prepare($sql)->execute();
    }

    /**
     * @return void
     */
    public function createHistoryTable()
    {
        $db = static::getDB();

        $sql = 'CREATE TABLE IF NOT EXISTS history(
            id INT NOT NULL AUTO_INCREMENT,
            PRIMARY KEY(id),
            user_id INT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES user(id),
            type VARCHAR(255) NOT NULL,
            value DOUBLE NOT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        )';

        $db->prepare($sql)->execute();

        $sql = 'CREATE INDEX `idx-history-user_id`
            ON history(user_id)';

        $db->prepare($sql)->execute();
    }
}

app/models/User.php
<?php

namespace app\models;

use PDO;
use core\base\Session;
use core\base\Model;
use core\helpers\ArrayHelper;

/**
 *
 */
class User extends Model
{
    /**
     * @var mixed
     */
    private static $_user;

    /**
     * @var void
     */
    public static function addBalance($user_id, $value)
    {
        $db = static::getDB();

        try {
            $db->beginTransaction();

            $st = $db->prepare('UPDATE user SET balance = ROUND(balance + ?, 2) WHERE id = ?');
            $st->execute([$value, $user_id]);

            $st = $db->prepare('INSERT INTO history(user_id, type, value) VALUES(?, ?, ?)');
            $st->execute([$user_id, 'add', $value]);

            $db->commit();
        } catch (\PDOException $e) {
            $db->rollBack();
        }
    }

    /**
     * @var boolean
     */
    public static function subBalance($user_id, $value)
    {
        $db = static::getDB();

        $result = false;

        try {
            $db->beginTransaction();

            $st = $db->prepare('SELECT balance FROM user WHERE id = ? FOR UPDATE');
            $st->execute([$user_id]);

            $balance = $st->fetchColumn();

            if ($balance === false) {
                throw new \Exception('user not found');
            }

            $max_balance = round($balance / 1.01, 2);

            if ($max_balance < $value) {
                throw new \Exception('balance not enough');
            }

            $commission = round($value * 0.01, 2);

            $st = $db->prepare('UPDATE user SET balance = ROUND(balance - ?, 2) WHERE id = ?');

            $st->execute([$value, $user_id]);
            $st->execute([$commission, $user_id]);

            $st = $db->prepare('INSERT INTO history(user_id, type, value) VALUES(?, ?, ?)');

            $st->execute([$user_id, 'sub', $value]);
            $st->execute([$user_id, 'sub', $commission]);

            $result = true;

            $db->commit();
        } catch (\Exception $e) {
            $db->rollBack();
        }

        return $result;
    }

    /**
     * @return mixed
     */
    public static function getUser()
    {
        $user_id = Session::get('user_id');

        if (empty($user_id)) {
            return false;
        }

        if (isset(static::$_user)) {
            return static::$_user;
        }

        $db = static::getDB();

        $st = $db->prepare('SELECT * FROM user WHERE id = ?');
        $st->execute([$user_id]);

        $result = $st->fetch(PDO::FETCH_ASSOC);

        if (empty($result)) {
            return false;
        } else {
            static::$_user = $result;
        }

        return static::$_user;
    }

    /**
     * @return string
     */
    public static function passwordHash($password)
    {
        return md5($password);
    }

    /**
     * @return boolean
     */
    public static function login($username, $password)
    {
        $db = static::getDB();

        $st = $db->prepare('SELECT * FROM user WHERE username = ?');
        $st->execute([$username]);

        $user = $st->fetch(PDO::FETCH_ASSOC);

        if (empty($user)) {
            return false;
        }

        if ($user['password'] != User::passwordHash($password)) {
            return false;
        }

        Session::set('user_id', $user['id']);

        return true;
    }

    /**
     * @return boolean
     */
    public static function logout()
    {
        return Session::destroy();
    }
}

app/controllers/SiteController.php
<?php

namespace app\controllers;

use core\base\Controller;
use app\models\User;

/**
 *
 */
class SiteController extends Controller
{
    /**
     *
     */
    public function actionIndex()
    {
        $user = User::getUser();

        return $this->render('index', [
            'user' => $user,
        ]);
    }
}

app/controllers/UserController.php
<?php

namespace app\controllers;

use core\base\Controller;
use core\helpers\ArrayHelper;
use app\models\User;

/**
 *
 */
class UserController extends Controller
{
    /**
     *
     */
    public function actionLogin()
    {
        if (User::getUser()) {
            return $this->goHome();
        }

        $error = null;

        if (!empty($_POST['User'])) {
            $username = ArrayHelper::getValue($_POST['User'], 'username');
            $password = ArrayHelper::getValue($_POST['User'], 'password');

            if (!User::login($username, $password)) {
                $error = 'Неправильное имя пользователя или пароль.';
            } else {
                return $this->goHome();
            }
        }

        return $this->render('login', [
            'error' => $error,
        ]);
    }

    /**
     *
     */
    public function actionLogout()
    {
        User::logout();

        return $this->goHome();
    }

    /**
     *
     */
    public function actionAddBalance()
    {
        $user = User::getUser();

        if (!$user) {
            return $this->goHome();
        }

        if (!empty($_POST['User'])) {
            $balance = ArrayHelper::getValue($_POST['User'], 'balance');
            $balance = str_replace(' ', '', $balance);

            if (is_numeric($balance) && $balance > 0) {
                User::addBalance($user['id'], round($balance, 2));

                return $this->redirect('/user/add-balance?success=1');
            }
        }

        return $this->render('add-balance', [
            'user' => $user,
        ]);
    }

    /**
     *
     */
    public function actionSubBalance()
    {
        $user = User::getUser();

        if (!$user) {
            return $this->goHome();
        }

        $error = null;

        if (!empty($_POST['User'])) {
            $balance = ArrayHelper::getValue($_POST['User'], 'balance');
            $balance = str_replace(' ', '', $balance);

            if (is_numeric($balance) && $balance > 0) {
                $balance = round($balance, 2);
                $max_balance = round($user['balance'] / 1.01, 2);

                if ($balance > $max_balance) {
                    $error = 'Максимальная сумма которую вы можете вывести: ' . number_format($max_balance, 2, '.', ' ');
                } else {
                    User::subBalance($user['id'], round($balance, 2));

                    return $this->redirect('/user/sub-balance');
                }
            }
        }

        return $this->render('sub-balance', [
            'error' => $error,
            'user' => $user,
        ]);
    }

    /**
     *
     */
    public function actionQueue()
    {
        $user = User::getUser();

        if (!$user) {
            return $this->goHome();
        }

        $queue = BalanceQueue::getAll();

        return $this->render('queue', [
            'queue' => $queue,
            'user' => $user,
        ]);
    }
}

app/views/layouts/main.php
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Test-task</title>
        <link rel="stylesheet" href="/css/bootstrap.css">
        <link rel="stylesheet" href="/css/style.css">
    </head>
    <body>
        <div class="main">
            <?= $content ?>
        </div>
    </body>
</html>

app/views/site/error.php
<h1>Fatal error</h1>
<p>Uncaught exception: <?= get_class($exception) ?></p>
<p>Message: <?= $exception->getMessage() ?></p>
<p>Stack trace:<pre><?= $exception->getTraceAsString() ?></pre></p>
<p>Thrown in <?= $exception->getFile() ?> on line <?= $exception->getLine() ?></p>

app/views/site/index.php
<?php if ($user === false): ?>
    <p class="alert alert-danger">Вы не авторизованы.</p>
    <a href="/user/login" class="btn btn-success">Войти <span class="glyphicon glyphicon-log-in"></span></a>
<?php else: ?>
    <p class="text-right">
        <a href="/user/logout" class="btn btn-sm btn-danger">Выход (<?= $user['username'] ?>)</a>
    </p>

    <p class="alert alert-info">Ваш баланс: <?= number_format($user['balance'], 2, '.', ' ') ?></p>
    <p>
        <a href="/user/add-balance" class="btn btn-success">Пополнить</a>
        <a href="/user/sub-balance" class="btn btn-primary">Вывести</a>
    </p>
<?php endif ?>

app/views/user/add-balance.php
<p class="text-left">
    <a href="/" class="btn btn-sm btn-success">Главная</a>
    <a href="/user/logout" class="btn btn-sm btn-danger">Выход (<?= $user['username'] ?>)</a>
</p>

<p>Ваш баланс: <?= number_format($user['balance'], 2, '.', ' ') ?></p>

<form method="post">
    <div class="form-group">
        <label for="user-balance">Пополнить на сумму</label>
        <input class="form-control" name="User[balance]" id="user-balance" placeholder="Пополнить на сумму">
    </div>

    <button type="submit" class="btn btn-primary">Пополнить</button>
</form>

app/views/user/login.php
<?php if (!empty($error)): ?>
    <p class="alert alert-danger"><?= $error ?></p>
<?php endif ?>

<form method="post">
    <div class="form-group">
        <label for="user-username">Имя пользователя</label>
        <input class="form-control" name="User[username]" id="user-username" placeholder="Имя пользователя">
    </div>

    <div class="form-group">
        <label for="user-password">Пароль</label>
        <input type="password" class="form-control" name="User[password]" id="user-password" placeholder="Пароль">
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Войти</button>
    </div>
</form>

<p>Вы можете войти в систему с помощью <strong>demo/demo</strong></p>

app/views/user/sub-balance.php
<p class="text-left">
    <a href="/" class="btn btn-sm btn-success">Главная</a>
    <a href="/user/logout" class="btn btn-sm btn-danger">Выход (<?= $user['username'] ?>)</a>
</p>

<?php if ($error): ?>
    <p class="alert alert-danger"><?= $error ?></p>
<?php endif ?>

<p>Ваш баланс: <?= number_format($user['balance'], 2, '.', ' ') ?></p>

<form method="post">
    <div class="form-group">
        <label for="user-balance">Вывести сумму</label>
        <input class="form-control" name="User[balance]" id="user-balance" placeholder="Вывести сумму">
    </div>

    <button type="submit" class="btn btn-primary">Вывести</button>
</form>